### ISSUE TITLE
Nachdem runterscrollen sieht es  verzerrt aus:

### ISSUE THREAD

**Issue by malvela** [Estimation-product-quality-features/Flour-Quality-inFeedProcessing#21]
![grafik](https://user-images.githubusercontent.com/68553692/156576125-96b61e53-e97b-4739-b99a-445c9f4c60cc.png)

**Comment by Hannes-G** [comment]
Komisch bei mir nicht, wenn ich auf den Link "Visit this site here" klicke komme ich zur landing page mit spinner und über Contact dann auf die Kontakt Seite:
![screenshot_contact_page](https://user-images.githubusercontent.com/53696641/156592674-d1e72032-0d67-4355-b3fc-3cfd2a930edd.png)

**Comment by malvela** [comment]
falsch ausgedruckt: ich meine, das 1.mal auf contact or team klicke, dann sieht man die vollständige Seite nicht bzw. wird von unten nach oben angezeigt, dann muss man nach oben scrollen um die Seite vollständig zu sehen

**Comment by Hannes-G** [comment]
Erledingt
