### ISSUE TITLE
die TF Version der vorhandenen RCNN prüfen

### ISSUE THREAD

**Issue by malvela** [Estimation-product-quality-features/Flour-Quality-inFeedProcessing#27]

**Comment by malvela** [comment]
Modelle sind in https://cloud.bik.biba.uni-bremen.de/s/qaNeenCbJsxFH5t zu finden

**Comment by malvela** [comment]
Vllt Interessant - https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html

**Comment by Hannes-G** [comment]
Erledigt, model läuft
